stages:
  - build
  - test
  
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay

Docker Build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:latest .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:latest
    - if [[ ! -z "${CI_COMMIT_TAG}" ]];
      then docker tag
         ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}-${DEPLOY_WHICH}:latest
         ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}-${DEPLOY_WHICH}:${CI_COMMIT_TAG};
      else docker tag
         ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:latest
         ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}; fi
    - if [[ ! -z "${CI_COMMIT_TAG}" ]];
      then docker push
         ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}-${DEPLOY_WHICH}:${CI_COMMIT_TAG};
      else docker push
         ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}-${DEPLOY_WHICH}:${CI_COMMIT_REF_SLUG}; fi
  tags:
    - docker
